import Foundation

/// GitHub-style `:shortcode:` names for the emoji people actually type.
/// Single code points only, so each draws as one glyph in the editor.
public enum Emoji {
    public static let shortcodes: [String: String] = [
        // Faces
        "smile": "😄", "smiley": "😃", "grinning": "😀", "grin": "😁", "laughing": "😆", "joy": "😂",
        "rofl": "🤣", "sweat_smile": "😅", "wink": "😉", "blush": "😊", "innocent": "😇",
        "slightly_smiling_face": "🙂", "upside_down_face": "🙃", "heart_eyes": "😍", "star_struck": "🤩",
        "kissing_heart": "😘", "yum": "😋", "stuck_out_tongue": "😛", "stuck_out_tongue_winking_eye": "😜",
        "zany_face": "🤪", "thinking": "🤔", "hugs": "🤗", "shushing_face": "🤫", "neutral_face": "😐",
        "expressionless": "😑", "no_mouth": "😶", "smirk": "😏", "unamused": "😒", "roll_eyes": "🙄",
        "grimacing": "😬", "relieved": "😌", "pensive": "😔", "sleepy": "😪", "sleeping": "😴",
        "mask": "😷", "nerd_face": "🤓", "sunglasses": "😎", "confused": "😕", "worried": "😟",
        "frowning_face": "🙁", "open_mouth": "😮", "hushed": "😯", "astonished": "😲", "flushed": "😳",
        "pleading_face": "🥺", "fearful": "😨", "cold_sweat": "😰", "cry": "😢", "sob": "😭",
        "scream": "😱", "confounded": "😖", "persevere": "😣", "disappointed": "😞", "sweat": "😓",
        "weary": "😩", "tired_face": "😫", "yawning_face": "🥱", "triumph": "😤", "rage": "😡",
        "angry": "😠", "skull": "💀", "poop": "💩", "clown_face": "🤡", "ghost": "👻", "alien": "👽",
        "robot": "🤖", "see_no_evil": "🙈", "hear_no_evil": "🙉", "speak_no_evil": "🙊", "partying_face": "🥳",
        "exploding_head": "🤯", "cowboy_hat_face": "🤠", "monocle_face": "🧐", "melting_face": "🫠",
        // Hands and people
        "+1": "👍", "thumbsup": "👍", "-1": "👎", "thumbsdown": "👎", "ok_hand": "👌", "wave": "👋",
        "clap": "👏", "raised_hands": "🙌", "pray": "🙏", "muscle": "💪", "point_up": "👆",
        "point_down": "👇", "point_left": "👈", "point_right": "👉", "fist": "👊", "crossed_fingers": "🤞",
        "v": "✌", "metal": "🤘", "call_me_hand": "🤙", "writing_hand": "✍", "handshake": "🤝",
        "eyes": "👀", "brain": "🧠", "man_shrugging": "🤷", "facepalm": "🤦", "raising_hand": "🙋",
        // Hearts and symbols
        "heart": "❤", "orange_heart": "🧡", "yellow_heart": "💛", "green_heart": "💚", "blue_heart": "💙",
        "purple_heart": "💜", "black_heart": "🖤", "white_heart": "🤍", "broken_heart": "💔",
        "sparkling_heart": "💖", "100": "💯", "boom": "💥", "collision": "💥", "sparkles": "✨",
        "star": "⭐", "star2": "🌟", "dizzy": "💫", "zap": "⚡", "fire": "🔥", "tada": "🎉",
        "confetti_ball": "🎊", "balloon": "🎈", "gift": "🎁", "trophy": "🏆", "medal_sports": "🏅",
        "1st_place_medal": "🥇", "white_check_mark": "✅", "heavy_check_mark": "✔", "ballot_box_with_check": "☑",
        "x": "❌", "negative_squared_cross_mark": "❎", "heavy_plus_sign": "➕", "heavy_minus_sign": "➖",
        "question": "❓", "grey_question": "❔", "exclamation": "❗", "bangbang": "‼", "warning": "⚠",
        "no_entry": "⛔", "no_entry_sign": "🚫", "stop_sign": "🛑", "construction": "🚧", "rotating_light": "🚨",
        "bulb": "💡", "memo": "📝", "pencil": "📝", "pencil2": "✏", "pushpin": "📌", "round_pushpin": "📍",
        "paperclip": "📎", "link": "🔗", "lock": "🔒", "unlock": "🔓", "key": "🔑", "hammer": "🔨",
        "wrench": "🔧", "gear": "⚙", "bug": "🐛", "rocket": "🚀", "package": "📦", "inbox_tray": "📥",
        "outbox_tray": "📤", "email": "📧", "calendar": "📆", "date": "📅", "chart_with_upwards_trend": "📈",
        "chart_with_downwards_trend": "📉", "bar_chart": "📊", "clipboard": "📋", "book": "📖",
        "books": "📚", "bookmark": "🔖", "label": "🏷", "mag": "🔍", "bell": "🔔", "mega": "📣",
        "speech_balloon": "💬", "thought_balloon": "💭", "hourglass": "⌛", "stopwatch": "⏱",
        "alarm_clock": "⏰", "computer": "💻", "keyboard": "⌨", "iphone": "📱", "camera": "📷",
        "art": "🎨", "musical_note": "🎵", "headphones": "🎧", "moneybag": "💰", "dollar": "💵",
        "gem": "💎", "crown": "👑", "lipstick": "💄", "recycle": "♻", "arrow_right": "➡",
        "arrow_left": "⬅", "arrow_up": "⬆", "arrow_down": "⬇", "arrows_counterclockwise": "🔄",
        "repeat": "🔁", "new": "🆕", "free": "🆓", "up": "🆙", "cool": "🆒", "ok": "🆗", "sos": "🆘",
        "information_source": "ℹ", "copyright": "©", "registered": "®", "tm": "™",
        "red_circle": "🔴", "orange_circle": "🟠", "yellow_circle": "🟡", "green_circle": "🟢",
        "large_blue_circle": "🔵", "purple_circle": "🟣", "black_circle": "⚫", "white_circle": "⚪",
        // Nature, food, travel
        "sunny": "☀", "cloud": "☁", "umbrella": "☔", "snowflake": "❄", "rainbow": "🌈", "ocean": "🌊",
        "earth_africa": "🌍", "earth_americas": "🌎", "earth_asia": "🌏", "crescent_moon": "🌙",
        "seedling": "🌱", "evergreen_tree": "🌲", "deciduous_tree": "🌳", "cactus": "🌵", "herb": "🌿",
        "four_leaf_clover": "🍀", "maple_leaf": "🍁", "fallen_leaf": "🍂", "rose": "🌹", "sunflower": "🌻",
        "cherry_blossom": "🌸", "tulip": "🌷", "dog": "🐶", "cat": "🐱", "mouse": "🐭", "rabbit": "🐰",
        "fox_face": "🦊", "bear": "🐻", "panda_face": "🐼", "koala": "🐨", "tiger": "🐯", "lion": "🦁",
        "cow": "🐮", "pig": "🐷", "frog": "🐸", "monkey_face": "🐵", "chicken": "🐔", "penguin": "🐧",
        "bird": "🐦", "owl": "🦉", "unicorn": "🦄", "bee": "🐝", "butterfly": "🦋", "snail": "🐌",
        "turtle": "🐢", "snake": "🐍", "octopus": "🐙", "fish": "🐟", "whale": "🐳", "dolphin": "🐬",
        "crab": "🦀", "apple": "🍎", "green_apple": "🍏", "lemon": "🍋", "banana": "🍌", "watermelon": "🍉",
        "grapes": "🍇", "strawberry": "🍓", "cherries": "🍒", "peach": "🍑", "avocado": "🥑",
        "pizza": "🍕", "hamburger": "🍔", "fries": "🍟", "taco": "🌮", "sushi": "🍣", "ramen": "🍜",
        "cake": "🍰", "birthday": "🎂", "cookie": "🍪", "doughnut": "🍩", "coffee": "☕", "tea": "🍵",
        "beer": "🍺", "beers": "🍻", "wine_glass": "🍷", "champagne": "🍾", "tropical_drink": "🍹",
        "car": "🚗", "taxi": "🚕", "bus": "🚌", "train": "🚆", "airplane": "✈", "ship": "🚢",
        "bike": "🚲", "house": "🏠", "office": "🏢", "hospital": "🏥", "school": "🏫",
        "soccer": "⚽", "basketball": "🏀", "football": "🏈", "tennis": "🎾", "video_game": "🎮",
        "dart": "🎯", "chess_pawn": "♟", "jigsaw": "🧩",
    ]
}
